### ISSUE TITLE
[AutoBuild v20181013.1] Modifying/saving Config.xml using Settings tab completely destroys all functionality

### ISSUE THREAD

**Issue by kmillerdevx3** [MalukuSeito/Character-Builder-5#10]
I got tired of changing the source from Custom Source on every screen, so I changed the config to make my current source the default.

After doing so, the current instance of CBB was fine (because the configuration had already been loaded) but new instances of CBB or of CB5 would fail to load any files and ultimately report all manner of bizarre errors on every file in my sources.

Having restored a backup of the Config.xml, everything started working again.

It appears that the Config.xml file created by CBB has a number of changes in it that are not in the version distributed with the application. Some of these are duplicates of existing entries, which causes some errors (duplicate dictionary entries). Further, when I removed the "old" version of duplicate settings, the app would still not function. It therefore appears that the modifications created by CBB are not in a schema that either CBB or CB5 expect to load.

**Comment by MalukuSeito** [comment]
I haven’t tested writing the config with CBB for quite some time, good find. I will check it out.

In the meantime, you don‘t have to save the default source in CBB for it to work, just change it and it should appear on any new screen.
You can also quickly change the source of a bunch of files by just renaming the folder in windows, CBB and CB5 will change the source to the new name while loading. Very helpful when you forget to change the source in a bunch of files.

**Comment by MalukuSeito** [comment]
Uploaded a fix to master,
