### ISSUE TITLE
[Suggestions]PDF Improvements/Equipment Tracking

### ISSUE THREAD

**Issue by MrSirDrDaddy** [MalukuSeito/Character-Builder-5#11]
I've been using this a great deal and currently I think the PDF fields still need some optimization improvements. Having full descriptions of keywords for every item in the player's current inventory is cumbersome to look at on a sheet and massively unnecessary (such as "heavy, two-handed, range 20/60"). An option to have items displayed by just the item name in the PDF inventory would be nice. It would also be nice to allow an option to only print the names of features and abilities instead of full descriptions if someone wants to save room at higher levels instead of print the full descriptions in impossibly tiny text. While it's possible to output an editable PDF, it would be better to not have to put the onus on the player to handle this and rather just have selectable options in the new PDF print menu.

Also PDFs currently tend to prioritize putting Bonus Spells in the attack boxes over equipped weapons. Even if that spell is 1/day or something like Light. Bonus Spell descriptions of their stats and effects should just be added to their spellbook sheet/spellcard sheet.

The last issue is that equipment is still handled awkwardly. When deleting a starting item it never removes from inventory and instead just adds the "(lost)" tag to it. This is very unnecessary and also doesn't remove the item's weight from a character. Multiple "lost" items also don't stack, turning them into a long list. The lost tag would be better off removed and replaced with the ability to remove any item from inventory. 

A massive improvement to the shop would be to add a feature to actually "buy" an item with current coinage if the item has a gp value set. This would allow the players to do direct shopping in-app with anything that has a set value instead of needing to do the math themselves and use the add feature. Allow for both buy and add would be preferable.

I hope these suggestions are helpful. They are the major things I get as feedback from my players and my own use of the app when creating characters or using it to run them.

**Comment by MalukuSeito** [comment]
These are very helpful,
The PDF extensions I will do, I always wanted to add an options to sort the attacks/bonus spells.
Just displaying the name is a great idea.

Deleting items is sadly awkward, but I might add an option to hide lost items, they also should never count towards weight. There is already an option to remove all starting equipment in the house rules options. 
There is a buy button in the shop for anything that has gold amount attached to it. Sadly there is no clear gold amount for magic items (maybe I missed that), so I couldn't add those. But weapons and such can be bought and even add a journal entry that removes the gold.

**Comment by MalukuSeito** [comment]
Got this done for the Windows version (App version some other time, not too hard). Even added an option to hide lost items (on by default)
Feedback appreciated

**Comment by MrSirDrDaddy** [comment]
This is great, perfect as far as I can tell.
    On Saturday, March 2, 2019, 10:59:03 AM CST, Marc-Sebastian Lucksch <notifications@github.com> wrote:  
 
 
Closed #11.

**Comment by MalukuSeito** [comment]
Good to hear
