### ISSUE TITLE
[Feature Request] Automatic level up

### ISSUE THREAD

**Issue by yodaldevoid** [MalukuSeito/Character-Builder-5#7]
It would be useful to have some way to set a character to the correct experience for a level for those of us who don't track experience.

**Comment by MalukuSeito** [comment]
You actually can, if you use the up/down buttons on the experience input field it jumps to the next/previous level.
![grafik](https://user-images.githubusercontent.com/17147116/40056799-c4f52974-584c-11e8-8cd8-c79c2f8316c7.png)

**Comment by MalukuSeito** [comment]
If anything I will probably use the stuff I had to make for the APP to make a new WPF-based Windows UI anyway. Sadly I am not an UI Designer, I really wish I was better at it.
