### ISSUE TITLE
[Issue/Suggestion] Guide for Sorce Data creation

### ISSUE THREAD

**Issue by SoraDrebin** [MalukuSeito/Character-Builder-5#9]
i'm decently savvy, speaking in terms of coding, but i'm trying to input data and not sure how do input a few specific things, like a Subclass that alters the Hit Die for its class.

a guide on how to input things would be extremely helpful to those not as coding savvy as others

**Comment by MalukuSeito** [comment]
Hmm, I have never seen a subclass that modifies it's base class hit die, so I haven't put in an option for that. Is that something that is generally needed?
